# Generated by Django 4.2.16 on 2024-11-08 13:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='file_uploads/')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
