# Generated by Django 4.2.16 on 2024-10-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LLM_Metadata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
