# Generated by Django 4.2.16 on 2024-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM_Metadata', '0006_alter_conversation_options_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='top_k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='top_p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
